#!/bin/bash
for i in $( ls ); do
   echo item: $i
done

///////////////

#!/bin/bash
for i in $( cat list ); do
   youtube-dl $i
done

///////////////
#Trouver(find) dans le repertoire en cours(./) tous les fichier png(-name "*.png"), 
#puis(-exec) extraire leur palette(palette) de couleur sans limite(-t 0) recursivement ({}) et terminer le exec (\;)
#!/bin/bash
find ./ -name "*.png" -exec palette -t 0 {} \;

///////////////

# Rewrite using xargs
# parallel work 
# multithread
