#!/bin/bash
for i in $( ls ); do
   echo item: $i
done

///////////////

#!/bin/bash
for i in $( cat list ); do
   youtube-dl $i
done

///////////////
#Trouver(find) dans le repertoire en cours(./) tous les fichier png(-name "*.png"), 
#puis(-exec) extraire leur palette(palette) de couleur sans limite(-t 0) recursivement ({}) et terminer le exec (\;)
#!/bin/bash
find ./ -name "*.png" -exec palette -t 0 {} \;

///////////////
for var in `find . -type f -name "*(1).m4a"`; do
    new=`echo $var | cut -d'(' -f1`;
    mv $var $new.m4a;
done
///////////////////
#Remove .1 at end of filename = modify extension 
#!/bin/env bash
for var in `find . -type f -name "*.1"`; do
    new=`echo $var | sed 's/.1//'`;
    mv $var $new;
done

# Rewrite using xargs
# parallel work 
# multithread
